server:
  port: 30401

# spring 配置
spring:
  application:
    name: alinesno-infra-ops-logback-boot
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dev_alinesno_infra_ops_logback_v100?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: adminer
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local
      database: 3
  kafka:
    bootstrap-servers: 192.168.101.18:9092
    consumer:
      group-id: infra_logback

# 日志队列配置
alinesno.logback:
  model: redis  # redis列队|kafka列队

actable:
  table:
    auto: update # create
  model:
    pack: com.alinesno.infra.ops.logback.entity
  database:
    type: mysql
  index:
    prefix: alinesno_ops_logback_idx_
  unique:
    prefix: alinesno_ops_logback_uni_

# sa-token配置
sa-token:
  token-name: satoken
  host-path: http://alinesno-infra-base-identity-auth-application.beta.base.infra.linesno.com
  sso:
    auth-url: ${sa-token.host-path}/login
    is-http: true
    check-ticket-url: ${sa-token.host-path}/sso/checkTicket
    slo-url: ${sa-token.host-path}/sso/signout
    get-data-url: ${sa-token.host-path}/sso/getData
  sign:
    secret-key:
