server:
  port: 30401

# spring 配置
spring:
  application:
    name: alinesno-infra-ops-logback-boot
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    url: jdbc:clickhouse://192.168.101.18:8123/default
    username: default
    password:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local
  kafka:
    bootstrap-servers: 192.168.101.18:9092
    consumer:
      group-id: infra_logback

sa-token:
  is-print: false