server:
  port: 31401

# spring 配置
spring:
  application:
    name: alinesno-infra-ops-logback-collector
  devtools:
    restart:
      enabled: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local
  kafka:
    bootstrap-servers: 192.168.101.18:9092
    consumer:
      group-id: infra_logback

sa-token:
  is-print: false