CREATE TABLE IF NOT EXISTS `manager_account_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `operation` VARCHAR(255) DEFAULT NULL COMMENT '操作说明',
  `method_time` BIGINT COMMENT '执行时间',
  `method` VARCHAR(255) COMMENT '类方法',
  `params` TEXT COMMENT '请求参数',
  `method_desc` VARCHAR(255) COMMENT '方法描述',
  `record_type` VARCHAR(255) COMMENT '请求记录',
  `ip` VARCHAR(255) COMMENT '服务器IP',
  `url` VARCHAR(255) COMMENT '请求链接',
  `agent` VARCHAR(255) COMMENT '浏览器信息',
  `create_time` DATETIME COMMENT '添加时间',
  `account_id` VARCHAR(255) COMMENT '账户ID',
  `login_name` VARCHAR(255) COMMENT '登陆名',
  `account_name` VARCHAR(255) COMMENT '用户名',
  `role_power` VARCHAR(255) COMMENT '角色权限',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='manager_account_record';


CREATE TABLE IF NOT EXISTS `business_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `log_id` VARCHAR(255) COMMENT '日志ID',
  `timestamp` BIGINT COMMENT '时间戳',
  `log_level` VARCHAR(255) COMMENT '日志级别',
  `log_source` VARCHAR(255) COMMENT '日志来源',
  `user_id` VARCHAR(255) COMMENT '用户ID',
  `operation_type` VARCHAR(255) COMMENT '操作类型',
  `operation_object` VARCHAR(255) COMMENT '操作对象',
  `operation_description` VARCHAR(255) COMMENT '操作描述',
  `request_parameters` VARCHAR(255) COMMENT '请求参数',
  `response_result` VARCHAR(255) COMMENT '响应结果',
  `exception_info` VARCHAR(255) COMMENT '异常信息',
  `ip_address` VARCHAR(255) COMMENT 'IP地址',
  `device_info` VARCHAR(255) COMMENT '设备信息',
  `location` VARCHAR(255) COMMENT '地理位置',
  `duration` BIGINT COMMENT '持续时间',
  `affected_objects` VARCHAR(255) COMMENT '受影响对象',
  `log_tags` VARCHAR(255) COMMENT '日志标签',
  `additional_info` VARCHAR(255) COMMENT '日志附加信息',
  `source_application` VARCHAR(255) COMMENT '日志来源应用',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='business_log';


CREATE TABLE IF NOT EXISTS `database_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `timestamp` TIMESTAMP COMMENT '时间戳',
  `log_level` VARCHAR(255) COMMENT '日志级别',
  `operation_type` VARCHAR(255) COMMENT '操作类型',
  `operation_object` VARCHAR(255) COMMENT '操作对象',
  `sql_statement` VARCHAR(255) COMMENT 'SQL语句',
  `parameters` VARCHAR(255) COMMENT '参数',
  `result` VARCHAR(255) COMMENT '返回结果',
  `execution_time` BIGINT COMMENT '执行时间',
  `exception` VARCHAR(255) COMMENT '异常信息',
  `username` VARCHAR(255) COMMENT '用户名',
  `ip_address` VARCHAR(255) COMMENT 'IP地址',
  `database_name` VARCHAR(255) COMMENT '数据库名',
  `table_name` VARCHAR(255) COMMENT '表名',
  `primary_key_value` VARCHAR(255) COMMENT '主键值',
  `source_application` VARCHAR(255) COMMENT '日志来源应用程序',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='database_log';


CREATE TABLE IF NOT EXISTS `inspection_data` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(255) COMMENT '巡检名称',
  `name_code` VARCHAR(255) COMMENT '巡检名称',
  `json_data` VARCHAR(255) COMMENT '巡检数据',
  `bus_type` VARCHAR(255) COMMENT '业务类型',
  `run_status` VARCHAR(255) COMMENT '运行状态',
  `total_time` VARCHAR(255) COMMENT '业务类型',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='inspection_data';


CREATE TABLE IF NOT EXISTS `io_list` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(255) COMMENT 'URL名称',
  `entry_type` VARCHAR(255) COMMENT 'IO类型',
  `start_time` DOUBLE COMMENT '开始时间',
  `duration` DOUBLE COMMENT '持续时间',
  `initiator_type` VARCHAR(255) COMMENT '初始化类型',
  `next_hop_protocol` VARCHAR(255) COMMENT '下一跳协议',
  `render_blocking_status` VARCHAR(255) COMMENT '渲染阻塞状态',
  `worker_start` DOUBLE COMMENT 'Worker开始时间',
  `redirect_start` DOUBLE COMMENT '重定向开始时间',
  `redirect_end` DOUBLE COMMENT '重定向结束时间',
  `fetch_start` DOUBLE COMMENT '获取开始时间',
  `domain_lookup_start` DOUBLE COMMENT '域名查询开始时间',
  `domain_lookup_end` DOUBLE COMMENT '域名查询结束时间',
  `connect_start` DOUBLE COMMENT '连接开始时间',
  `connect_end` DOUBLE COMMENT '连接结束时间',
  `secure_connection_start` DOUBLE COMMENT '安全连接开始时间',
  `request_start` DOUBLE COMMENT '请求开始时间',
  `response_start` DOUBLE COMMENT '响应开始时间',
  `response_end` DOUBLE COMMENT '响应结束时间',
  `transfer_size` INT COMMENT '传输大小',
  `encoded_body_size` INT COMMENT '编码后的主体大小',
  `decoded_body_size` INT COMMENT '解码后的主体大小',
  `server_timing` VARCHAR(255) COMMENT '服务器计时信息',
  `unload_event_start` DOUBLE COMMENT '卸载事件开始时间',
  `unload_event_end` DOUBLE COMMENT '卸载事件结束时间',
  `dom_interactive` DOUBLE COMMENT 'DOM可交互时间',
  `dom_content_loaded_event_start` DOUBLE COMMENT 'DOM内容加载事件开始时间',
  `dom_content_loaded_event_end` DOUBLE COMMENT 'DOM内容加载事件结束时间',
  `dom_complete` DOUBLE COMMENT 'DOM完成时间',
  `load_event_start` DOUBLE COMMENT '页面加载事件开始时间',
  `load_event_end` DOUBLE COMMENT '页面加载事件结束时间',
  `type` VARCHAR(255) COMMENT '类型',
  `redirect_count` INT COMMENT '重定向次数',
  `activation_start` DOUBLE COMMENT '激活开始时间',
  `log_type` VARCHAR(255) COMMENT '日志类型',
  `time_step` BIGINT COMMENT '时间步长',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IO信息实体类';


CREATE TABLE IF NOT EXISTS `a_log_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `timestamp` BIGINT COMMENT '时间戳',
  `log_level` VARCHAR(255) COMMENT '日志级别',
  `logger_name` VARCHAR(255) COMMENT '日志来源',
  `thread_name` VARCHAR(255) COMMENT '线程名',
  `log_message` VARCHAR(255) COMMENT '日志消息',
  `exception` VARCHAR(255) COMMENT '异常信息',
  `username` VARCHAR(255) COMMENT '用户名',
  `ip_address` VARCHAR(255) COMMENT 'IP地址',
  `request_url` VARCHAR(255) COMMENT '请求URL',
  `request_method` VARCHAR(255) COMMENT '请求方法',
  `request_parameters` VARCHAR(255) COMMENT '请求参数',
  `response_code` INT COMMENT '响应代码',
  `response_time` BIGINT COMMENT '响应时间',
  `server_name` VARCHAR(255) COMMENT '服务器名',
  `log_id` VARCHAR(255) COMMENT '日志ID',
  `log_tags` VARCHAR(255) COMMENT '日志标签',
  `source_application` VARCHAR(255) COMMENT '日志来源应用程序',
  `log_category` VARCHAR(255) COMMENT '日志分类',
  `log_location` VARCHAR(255) COMMENT '日志位置',
  `log_context` VARCHAR(255) COMMENT '日志上下文',
  `log_markers` VARCHAR(255) COMMENT '日志标记',
  `log_extra_data` VARCHAR(255) COMMENT '日志附加数据',
  `log_duration` BIGINT COMMENT '日志持续时间',
  `log_environment` VARCHAR(255) COMMENT '日志环境',
  `standardized_fields` VARCHAR(255) COMMENT '日志标准化字段',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='日志实体类';


CREATE TABLE IF NOT EXISTS `manager_login_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `login_name` VARCHAR(255) COMMENT '登陆名',
  `login_time` DATETIME COMMENT '登陆时间',
  `login_ip` VARCHAR(255) COMMENT '登陆IP',
  `login_status` VARCHAR(255) COMMENT '登陆状态(1成功|0失败)',
  `error_password` VARCHAR(255) COMMENT '错误密码',
  `phone_code` VARCHAR(255) COMMENT '手机验证码',
  `email_code` VARCHAR(255) COMMENT '邮箱验证码',
  `login_src` VARCHAR(255) COMMENT '登陆来源',
  `sign_out_time` DATETIME COMMENT '退出时间',
  `login_browser` VARCHAR(255) COMMENT '浏览器信息',
  `login_remark` VARCHAR(255) COMMENT '登陆备注',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户登陆记录表';


CREATE TABLE IF NOT EXISTS `log_type` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `TypeID` VARCHAR(255) COMMENT '类型ID',
  `TypeName` VARCHAR(255) COMMENT '类型名称',
  `Description` VARCHAR(255) COMMENT '描述',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='日志类型管理实体类';


CREATE TABLE IF NOT EXISTS `nginx_access_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `timestamp` TIMESTAMP COMMENT '时间戳',
  `client_ip_address` VARCHAR(255) COMMENT '客户端IP地址',
  `request_method` VARCHAR(255) COMMENT '请求方法',
  `request_url` VARCHAR(255) COMMENT '请求URL',
  `http_version` VARCHAR(255) COMMENT 'HTTP协议版本',
  `status_code` INT COMMENT '状态码',
  `response_size` BIGINT COMMENT '响应大小',
  `referer` VARCHAR(255) COMMENT '引荐来源',
  `user_agent` VARCHAR(255) COMMENT '用户代理',
  `response_time` BIGINT COMMENT '响应时间',
  `request_headers` VARCHAR(255) COMMENT '请求头',
  `response_headers` VARCHAR(255) COMMENT '响应头',
  `request_body` VARCHAR(255) COMMENT '请求体',
  `response_body` VARCHAR(255) COMMENT '响应体',
  `access_log_type` VARCHAR(255) COMMENT '访问日志类型',
  `hostname` VARCHAR(255) COMMENT '主机名',
  `port` INT COMMENT '端口号',
  `domain` VARCHAR(255) COMMENT '域名',
  `request_protocol` VARCHAR(255) COMMENT '请求协议',
  `request_time` TIMESTAMP COMMENT '请求时间',
  `response_time_stamp` TIMESTAMP COMMENT '响应时间',
  `server_name` VARCHAR(255) COMMENT '服务器名称',
  `cache_status` VARCHAR(255) COMMENT '缓存状态',
  `frontend_proxy` VARCHAR(255) COMMENT '前端代理',
  `backend_server` VARCHAR(255) COMMENT '后端服务器',
  `ssl_protocol_version` VARCHAR(255) COMMENT 'SSL协议版本',
  `ssl_cipher` VARCHAR(255) COMMENT 'SSL加密算法',
  `request_time_range` VARCHAR(255) COMMENT '请求时间区间',
  `request_duration` BIGINT COMMENT '请求时长',
  `response_type` VARCHAR(255) COMMENT '响应类型',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Nginx访问日志实体类';


CREATE TABLE IF NOT EXISTS `performance_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `fcp` DOUBLE COMMENT '首次内容绘制 (FCP)',
  `fp` INT COMMENT '白屏时间（FP）',
  `redirect_time` INT COMMENT '重定向耗时',
  `domain_lookup_time` INT COMMENT 'DNS查询耗时',
  `connect_time` INT COMMENT 'TCP链接耗时',
  `response_time` INT COMMENT 'HTTP请求耗时',
  `dom_complete_time` INT COMMENT 'DOM解析耗时',
  `ttfb` DOUBLE COMMENT '第一字节时间 (TTFB)',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='性能信息实体类';


CREATE TABLE IF NOT EXISTS `log_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_name` VARCHAR(255) COMMENT '任务名称',
  `cron_expression` VARCHAR(255) COMMENT '定时CRON表达式',
  `is_running` TINYINT(1) COMMENT '是否运行',
  `status` VARCHAR(255) COMMENT '运行状态',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='发送任务列表';


CREATE TABLE IF NOT EXISTS `terminal_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `resolving_power` VARCHAR(255) COMMENT '宽高比',
  `referrer` VARCHAR(255) COMMENT '引荐来源',
  `ua` VARCHAR(255) COMMENT '用户代理',
  `browser_name` VARCHAR(255) COMMENT '浏览器信息',
  `browser_version` VARCHAR(255) COMMENT '浏览器版本',
  `browser_major` VARCHAR(255) COMMENT '浏览器主要版本',
  `engine_name` VARCHAR(255) COMMENT '引擎信息',
  `engine_version` VARCHAR(255) COMMENT '引擎版本',
  `os_name` VARCHAR(255) COMMENT '系统信息',
  `os_version` VARCHAR(255) COMMENT '系统版本',
  `ip` VARCHAR(255) COMMENT 'IP地址',
  `city` VARCHAR(255) COMMENT '城市',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='终端信息实体类';
